hp_awards/urls.py
from django.urls import path
from . import views
from . import views_htmx

app_name = "hp_awards"
urlpatterns = [
    path("", views.home, name="home"),
    path("umum/", views.home_umum, name="umum"),
    path("mahasiswa/", views.home_mahasiswa, name="mahasiswa"),
    path("syarat-peserta/", views.syarat_peserta, name="syarat_peserta"),
    path("prinsip/", views.prinsip, name="prinsip"),
    path("tentang/", views.tentang, name="tentang"),
    path("kontak-kami/", views.kontak, name="kontak"),
    path("policy-questions/", views.policy_questions, name="policy_questions"),
    path("registrasi/", views.registrasi, name="registrasi"),
    path("list-submisi/", views.list_submisi, name="list_submisi"),
    path("submisi/<str:id_submisi>/", views.detail_submisi, name="detail_submisi"),
    path("submisi/<str:id_submisi>/edit/", views.edit_submisi, name="edit_submisi"),
    path("unggah-naskah/", views.unggah_naskah, name="unggah_naskah"),
    path(
        "submisi/<str:id_submisi>/set-juri/",
        views.tetapkan_reviewer,
        name="set_reviewer",
    ),
    path("submisi-set-gugur/", views.gugur_submisi, name="set_gugur"),
    path("submisi-set-nilai-abstrak/", views.tetapkan_nilai, name="set_nilai_abstrak"),
    path(
        "unduh-nilai-abstrak/",
        views.unduh_hasil_penilaian_abstrak,
        name="unduh_nilai_abstrak",
    ),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    # HTMX views response
    path("hx/get-stats/", views_htmx.get_stats, name="hx_get_stats"),
]

hp_awards_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


def _throw_error(request):
    raise Exception("exception raised.")


urlpatterns = [
    path("try-err/", _throw_error),
    path("admin-sibijaks/", admin.site.urls),
    path("", include("hp_awards.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

hp_awards/forms.py
from django import forms
from django.core.exceptions import ValidationError

from django_recaptcha.fields import ReCaptchaField
from django_recaptcha.widgets import ReCaptchaV3

from .models import Submisi, Reviewer, PolicyQuestion


class FormCaptcha(forms.Form):
    captcha = ReCaptchaField(widget=ReCaptchaV3)


class FormPendaftaran(forms.ModelForm):
    policy_question = forms.ModelChoiceField(
        queryset=PolicyQuestion.objects.order_by("id")
    )

    class Meta:
        model = Submisi
        fields = [
            "nama",
            "wa",
            "email",
            "kategori_pendaftar",
            "pendidikan",
            "pekerjaan",
            "afiliasi",
            # "topik",
            "policy_question",
            "policy_question_custom",
            # "swafoto",  # tidak pada saat registrasi awal
            "ktm",
            "judul_pb",
            "abstrak_pb",
        ]

    def clean(self):
        cleaned_data = super().clean()
        kategori_pendaftar = cleaned_data.get("kategori_pendaftar")
        ktm = cleaned_data.get("ktm")
        pekerjaan = cleaned_data.get("pekerjaan")
        # Mahasiswa butuh KTM/surket mhs
        if (kategori_pendaftar in (Submisi.MAHASISWA, Submisi.MAHASISWA2)) and not ktm:
            self.add_error(
                "ktm",
                "Kategori Mahasiswa harus menyertakan KTM atau surket mahasiswa",
            )

        # Umum harus mengisi kolom pekerjaan
        if kategori_pendaftar == Submisi.UMUM and not pekerjaan:
            self.add_error(
                "pekerjaan",
                "Kategori Umum harus mengisi nama profesi",
            )

        policy_question = cleaned_data.get("policy_question")
        policy_question_custom = cleaned_data.get("policy_question_custom")
        if (
            policy_question == PolicyQuestion.objects.get(pk=1)
            and not policy_question_custom
        ):
            self.add_error(
                "policy_question_custom",
                "Anda harus menuliskan Policy Question Anda jika memilih 'Lainnya'",
            )


class FormPenugasanJuri(forms.ModelForm):
    class Meta:
        model = Submisi
        fields = ["reviewers"]
        labels = {
            "reviewers": "Juri ditugaskan:",
        }


class FormUnggahFulltext(forms.ModelForm):
    class Meta:
        model = Submisi
        fields = ["file_pb_pdf", "file_pb_doc", "file_turnitin", "link_dakung"]
        labels = {
            "file_pb_pdf": "1. File Naskah format PDF",
            "file_pb_doc": "2. File Naskah format DOC/DOCX",
            "file_turnitin": "3. File Bukti Bebas Plagiarisme (misalnya Turnitin)",
            "link_dakung": "4. Link Apendiks dan Data Dukung (Jika Ada. Jangan lupa izinkan akses untuk panitia).",
        }


class FormUnggahPPT(forms.ModelForm):
    class Meta:
        model = Submisi
        fields = ["file_pb_ppt"]
        labels = {
            "file_pb_ppt": "1. File Bahan Tayang format Microsoft PowerPoint (PPT/PPTX)"
        }


class ReviewerForm(forms.ModelForm):
    # tidak perlu ada Meta karena
    # sejauh ini Form ini hanya untuk situs admin

    def clean_username(self):
        username = self.cleaned_data["username"]
        duplicate_found = Reviewer.objects.filter(username=username).exists()
        if duplicate_found and self.instance.pk is None:
            raise ValidationError("Reviewer dengan username yang sama sudah ada.")
        return username


class FormKontak(forms.Form):
    nama = forms.CharField(label="Nama", max_length=150, required=True)
    email = forms.EmailField(
        required=True, max_length=50, help_text="Kami akan merespon ke alamat email ini"
    )
    wa = forms.CharField(label="Nomor WA", max_length=20, required=False)
    pertanyaan = forms.CharField(required=True, widget=forms.Textarea)

hp_awards/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import (
    Case,
    When,
    Avg,
    Count,
    F,
    Q,
    FloatField,
    ExpressionWrapper,
    Sum,
)
from django.http import Http404, HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.utils import timezone

from bs4 import BeautifulSoup
from openpyxl import Workbook

from .forms import (
    FormPendaftaran,
    FormPenugasanJuri,
    FormCaptcha,
    FormKontak,
    FormUnggahFulltext,
    FormUnggahPPT,
)
from .models import Pernyataan, Submisi, Reviewer
from .helpers import kirim_konfirmasi_submisi, kirim_pertanyaan_pengunjung, Round

from datetime import datetime
import decimal


def home(request):
    context = {
        "page_title": "home",
    }
    return render(request, "hp_awards/home.html", context)


def home_umum(request):
    context = {
        "page_title": "umum",
    }
    return render(request, "hp_awards/home_umum.html", context)


def home_mahasiswa(request):
    context = {
        "page_title": "mahasiswa",
    }
    return render(request, "hp_awards/home_mahasiswa.html", context)


def syarat_peserta(request):
    return render(
        request,
        "hp_awards/syarat_peserta.html",
        {
            "page_title": "informasi",
        },
    )


def prinsip(request):
    return render(
        request,
        "hp_awards/prinsip.html",
        {
            "page_title": "informasi",
        },
    )


def tentang(request):
    return render(
        request,
        "hp_awards/tentang.html",
        {
            "page_title": "tentang",
        },
    )


def kontak(request):
    form = FormKontak()
    form_captcha = FormCaptcha()
    if request.method == "POST":
        form_captcha = FormCaptcha(request.POST)
        form = FormKontak(request.POST)
        if form_captcha.is_valid() and form.is_valid():
            nama = form.cleaned_data["nama"]
            email = form.cleaned_data["email"]
            pertanyaan = form.cleaned_data["pertanyaan"]
            kirim_pertanyaan_pengunjung(nama, email, pertanyaan)
            messages.info(request, "Pertanyaan Anda berhasil dikirim")
            form = None

    context = {
        "page_title": "informasi",
        "form": form,
        "form_captcha": form_captcha,
    }
    return render(request, "hp_awards/kontak.html", context)


def policy_questions(request):
    return render(
        request,
        "hp_awards/policy_questions.html",
        {
            "page_title": "informasi",
        },
    )


def registrasi(request):
    # handle pendaftaran jika sudah ditutup
    now = timezone.localtime()
    tanggal_tutup = timezone.make_aware(datetime(year=2024, month=7, day=21))
    if now >= tanggal_tutup:
        raise Http404("Periode registrasi sudah ditutup.")
    form = FormPendaftaran()
    form_captcha = FormCaptcha()
    if request.method == "POST":
        # verifikasi captcha
        # form_captcha = FormCaptcha(request.POST)
        # if not form_captcha.is_valid():
        #     messages.error(request, "Anda diduga Robot. Coba lagi lain waktu.")
        #     return redirect("hp_awards:registrasi")
        form = FormPendaftaran(request.POST, request.FILES)
        if form.is_valid():
            submisi = form.save(commit=True)
            # set kolaborators ke m2m rel
            zip_kolabs = zip(
                request.POST.getlist("kolab-nama"),
                request.POST.getlist("kolab-wa"),
                request.POST.getlist("kolab-email"),
            )
            for nama_kolab, wa_kolab, email_kolab in zip_kolabs:
                # hanya create kolabo jika ada nama kolabo-nya
                if nama_kolab:
                    _ = submisi.kolaborators.create(
                        nama=nama_kolab, wa=wa_kolab, email=email_kolab
                    )
            context = {
                "wa": submisi.wa,
                "email": submisi.email,
            }
            kirim_konfirmasi_submisi(submisi=submisi)
            return render(request, "hp_awards/registrasi_sukses.html", context)
    context = {
        "form": form,
        "form_captcha": form_captcha,
        "form_has_errors": form.errors,
        "pernyataans": Pernyataan.objects.all(),
        "page_title": "home",
        "hide_registration_navbar": True,
    }
    return render(request, "hp_awards/registrasi.html", context)


def list_submisi(request):
    context = {
        "page_title": "",
    }
    ctx = decimal.getcontext()
    ctx.rounding = decimal.ROUND_HALF_UP

    # jika user adalah staf/admin
    if request.user.is_staff:
        submisis = Submisi.objects.prefetch_related("reviewers", "penilaians")
        submisis = submisis.annotate(total_skor=Sum("penilaians__nilai3"))
        submisis = submisis.annotate(
            reviewer_menilai=Count("penilaians", filter=Q(penilaians__nilai3__gt=0))
        )
        submisis = submisis.annotate(
            rerata_skor=Case(
                When(reviewer_menilai=0, then=0.0),
                default=ExpressionWrapper(
                    F("total_skor") / F("reviewer_menilai"),
                    output_field=FloatField(),
                ),
            )
        )
        context["submisis"] = submisis.all().order_by(
            "-created_at", "kategori_pendaftar"
        )
        return render(request, "hp_awards/list_submisi_admin.html", context)

    # jika user adalah peserta
    if request.user.is_authenticated and request.session.get("role") == "user":
        wa = request.session.get("wa")
        email = request.session.get("email")
        submisis = Submisi.objects.filter(wa=wa, email=email)
        context["submisis"] = submisis
        context["ada_lolos"] = submisis.filter(status=Submisi.TUNGGU3).exists()

    # jika user adalah reviewer
    if request.user.is_authenticated and request.session.get("role") == "reviewer":
        reviewer = Reviewer.objects.prefetch_related(
            "penilaians", "penilaians__submisi"
        ).get(username=request.session["username_reviewer"])
        context["reviewer"] = reviewer
        context["todo_count"] = reviewer.penilaians.filter(
            string_nilai3__isnull=True, submisi__status=Submisi.TUNGGU3
        ).count()
        context["penilaians"] = reviewer.penilaians.filter(
            submisi__status=Submisi.TUNGGU3
        ).order_by("submisi__nama")
        return render(request, "hp_awards/list_submisi_reviewer.html", context)

    form_captcha = FormCaptcha()
    context["form_captcha"] = form_captcha
    if request.method == "POST":
        # handle POST dari form
        # check captcha
        # form_captcha = FormCaptcha(request.POST)
        # if not form_captcha.is_valid():
        #     messages.error(request, "Anda diduga Robot. Coba lagi lain waktu.")
        #     return redirect("hp_awards:list_submisi")
        wa = request.POST.get("wa")
        email = str(request.POST.get("email")).lower()
        if Submisi.objects.filter(wa=wa, email=email).exists():
            submisis = Submisi.objects.filter(wa=wa, email=email)
            # log in sebagai generic user
            user = authenticate(request, username="user", password="user")
            if user is not None:
                login(request, user)
                request.session["role"] = "user"
                request.session["wa"] = wa
                request.session["email"] = email
                request.session["nama_bar"] = email
            else:
                return HttpResponse("Basic user not found")
            context["submisis"] = submisis
            context["ada_lolos"] = submisis.filter(status=Submisi.TUNGGU3).exists()
    return render(request, "hp_awards/list_submisi.html", context)


@login_required
def detail_submisi(request, id_submisi):
    submisi = get_object_or_404(Submisi, kode_submisi=id_submisi)
    context = {
        "submisi": submisi,
        "submisi_class": Submisi,
        "form_naskah": FormUnggahPPT(instance=submisi),
    }
    try:
        url_pb_pdf = f"{request.scheme}://{request.get_host()}{submisi.file_pb_pdf.url}"
        url_pb_ppt = f"{request.scheme}://{request.get_host()}{submisi.file_pb_ppt.url}"
    except:
        url_pb_pdf = ""
        url_pb_ppt = ""
    context["url_pb_pdf"] = url_pb_pdf
    context["url_pb_ppt"] = url_pb_ppt

    if request.user.is_staff:
        context["form_penugasan_juri"] = FormPenugasanJuri(instance=submisi)
        context["reviewers"] = Reviewer.objects.all().order_by("nama")
        return render(request, "hp_awards/detail_submisi_admin.html", context)
        # NOTE handle POST penugasan juri di view func lain
    if request.session.get("role", False) == "reviewer":
        return render(request, "hp_awards/detail_submisi_reviewer.html", context)
    if request.session.get("role", False) == "admin":
        return render(request, "hp_awards/detail_submisi_admin.html", context)
    # default return adalah peserta
    return render(request, "hp_awards/detail_submisi.html", context)


def edit_submisi(request, id_submisi):
    # NOTE redir dulu yaa
    return redirect("hp_awards:home")
    submisi_manager = Submisi.objects.prefetch_related("kolaborators")
    submisi = get_object_or_404(submisi_manager, kode_submisi=id_submisi)
    form = FormPendaftaran(instance=submisi)
    if request.method == "POST":
        form = FormPendaftaran(request.POST, instance=submisi)
        if form.is_valid():
            submisi = form.save()
            # set kolaborators ke m2m rel
            zip_kolabs = zip(
                request.POST.getlist("kolab-nama"),
                request.POST.getlist("kolab-wa"),
                request.POST.getlist("kolab-email"),
            )
            # utk edit, hapus kolabos yang sudah ada
            _ = submisi.kolaborators.all().delete()
            submisi.kolaborators.clear()

hp_awards/templates/hp_awards/elem/form-penilaian-abstrak.html
<form method="POST" action="{% url 'hp_awards:set_nilai_abstrak' %}">
    {% csrf_token %}
    <input type="hidden" name="id_submisi" value="{{ submisi.kode_submisi }}">
    <table id="table-skor-abstrak" class="table table-hover table-bordered mb-5">
        <thead>
            <tr>
                <th rowspan="2" class="cell-center">Item Penilaian</th>
                <th colspan="5" class="text-center">Nilai (Skala Likert)</th>
            </tr>
            <tr>
                <th style="width: 100px;">Tertinggi</th>
                <th style="width: 100px;"></th>
                <th style="width: 100px;"></th>
                <th style="width: 100px;"></th>
                <th style="width: 100px;">Terendah</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td><b>Inovatif</b><br>Ide/gagasan memuat hal baru dalam menyelesaikan masalah yang ditemukan</td>
                <td>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" value="30" name="inovatif" id="idinovatif1">
                        <label class="form-check-label" for="idinovatif1">
                            5
                        </label>
                    </div>
                </td>
                <td>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" value="24" name="inovatif" id="idinovatif2">
                        <label class="form-check-label" for="idinovatif2">
                            4
                        </label>
                    </div>
                </td>
                <td>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" value="18" name="inovatif" id="idinovatif3">
                        <label class="form-check-label" for="idinovatif3">
                            3
                        </label>
                    </div>
                </td>
                <td>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" value="12" name="inovatif" id="idinovatif4">
                        <label class="form-check-label" for="idinovatif4">
                            2
                        </label>
                    </div>
                </td>
                <td>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" value="6" name="inovatif" id="idinovatif5" checked>
                        <label class="form-check-label" for="idinovatif5">
                            1
                        </label>
                    </div>
                </td>
            </tr>
            <tr>
                <td><b>Aplikatif</b><br>Ide/gagasan dapat diimplementasikan</td>
                <td>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" value="40" name="aplikatif" id="idaplikatif1">
                        <label class="form-check-label" for="idaplikatif1">
                            5
                        </label>
                    </div>
                </td>
                <td>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" value="32" name="aplikatif" id="idaplikatif2">
                        <label class="form-check-label" for="idaplikatif2">
                            4
                        </label>
                    </div>
                </td>
                <td>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" value="24" name="aplikatif" id="idaplikatif3">
                        <label class="form-check-label" for="idaplikatif3">
                            3
                        </label>
                    </div>
                </td>
                <td>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" value="16" name="aplikatif" id="idaplikatif4">
                        <label class="form-check-label" for="idaplikatif4">
                            2
                        </label>
                    </div>
                </td>
                <td>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" value="8" name="aplikatif" id="idaplikatif5" checked>
                        <label class="form-check-label" for="idaplikatif5">
                            1
                        </label>
                    </div>
                </td>
            </tr>
            <tr>
                <td><b>Kritis</b><br>Ide/gagasan berisi telaah kritis suatu permasalahan yang aktual sesuai tema dan policy question</td>
                <td>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" value="30" name="kritis" id="idkritis1">
                        <label class="form-check-label" for="idkritis1">
                            5
                        </label>
                    </div>
                </td>
                <td>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" value="24" name="kritis" id="idkritis2">
                        <label class="form-check-label" for="idkritis2">
                            4
                        </label>
                    </div>
                </td>
                <td>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" value="18" name="kritis" id="idkritis3">
                        <label class="form-check-label" for="idkritis3">
                            3
                        </label>
                    </div>
                </td>
                <td>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" value="12" name="kritis" id="idkritis4">
                        <label class="form-check-label" for="idkritis4">
                            2
                        </label>
                    </div>
                </td>
                <td>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" value="6" name="kritis" id="idkritis5" checked>
                        <label class="form-check-label" for="idkritis5">
                            1
                        </label>
                    </div>
                </td>
            </tr>
        </tbody>
    </table>
    <div class="mb-5 fs-5" id="skor-total">
        Total Skor = 
    </div>
    <!-- <span class="fs-5" style="color: red;">Penilaian yang sudah diberikan <b>tidak dapat diubah</b>. Mohon cek kembali
        isian Bapak/Ibu sebelum melanjutkan</span> -->
    <div class="d-grid gap-2">
        <button class="mt-3 btn btn-kemkes" type="submit">Simpan Penilaian</button>
    </div>
</form>

<script>
    $(document).ready(function () {

        // Function to calculate the sum of radio values
        function calculateSum() {
            var sum = 0;
            $("#table-skor-abstrak input:radio:checked").each(function () {
                sum += parseInt($(this).val(), 10);
            });
            return `Total Skor = ${sum}`;
        }

        // Update the sum on page load and whenever a radio button is clicked
        $("#skor-total").text(calculateSum());
        $("#table-skor-abstrak input:radio").click(function () {
            $("#skor-total").text(calculateSum());
        });
    });
</script>

hp_awards/templates/hp_awards/elem/meta.html
{% load static %}
<!-- Primary Meta Tags -->
<meta name="title" content="SiBijaKs Awards 2024" />
<meta name="description" content="SiBijaKs (Rekomendasi Kebijakan Kesehatan) Awards 2024 adalah kompetisi penulisan rekomendasi kebijakan kesehatan dengan data Survei Kesehatan Indonesia (SKI) tahun 2023 sebagai sumber data utama." />

<!-- Open Graph / Facebook -->
<meta property="og:type" content="website" />
<meta property="og:url" content="https://lombapb.bkpk.kemkes.go.id/" />
<meta property="og:title" content="SiBijaKs Awards 2024" />
<meta property="og:description" content="SiBijaKs (Rekomendasi Kebijakan Kesehatan) Awards 2024 adalah kompetisi penulisan rekomendasi kebijakan kesehatan dengan data Survei Kesehatan Indonesia (SKI) tahun 2023 sebagai sumber data utama." />
<meta property="og:image" content="https://lombapb.bkpk.kemkes.go.id{% static 'img/banner-mobile1.png' %}" />

<!-- Twitter -->
<meta property="twitter:card" content="summary_large_image" />
<meta property="twitter:url" content="https://lombapb.bkpk.kemkes.go.id/" />
<meta property="twitter:title" content="SiBijaKs Awards 2024" />
<meta property="twitter:description" content="SiBijaKs (Rekomendasi Kebijakan Kesehatan) Awards 2024 adalah kompetisi penulisan rekomendasi kebijakan kesehatan dengan data Survei Kesehatan Indonesia (SKI) tahun 2023 sebagai sumber data utama." />
<meta property="twitter:image" content="https://lombapb.bkpk.kemkes.go.id{% static 'img/banner-mobile1.png' %}" />