hp_awards/urls.py
from django.urls import path
from . import views
from . import views_htmx

app_name = "hp_awards"
urlpatterns = [
    path("", views.home, name="home"),
    path("umum/", views.home_umum, name="umum"),
    path("mahasiswa/", views.home_mahasiswa, name="mahasiswa"),
    path("syarat-peserta/", views.syarat_peserta, name="syarat_peserta"),
    path("prinsip/", views.prinsip, name="prinsip"),
    path("tentang/", views.tentang, name="tentang"),
    path("kontak-kami/", views.kontak, name="kontak"),
    path("policy-questions/", views.policy_questions, name="policy_questions"),
    path("registrasi/", views.registrasi, name="registrasi"),
    path("list-submisi/", views.list_submisi, name="list_submisi"),
    path("submisi/<str:id_submisi>/", views.detail_submisi, name="detail_submisi"),
    path("submisi/<str:id_submisi>/edit/", views.edit_submisi, name="edit_submisi"),
    path("unggah-naskah/", views.unggah_naskah, name="unggah_naskah"),
    path(
        "submisi/<str:id_submisi>/set-juri/",
        views.tetapkan_reviewer,
        name="set_reviewer",
    ),
    path("submisi-set-gugur/", views.gugur_submisi, name="set_gugur"),
    path("submisi-set-nilai-abstrak/", views.tetapkan_nilai, name="set_nilai_abstrak"),
    path(
        "unduh-nilai-abstrak/",
        views.unduh_hasil_penilaian_abstrak,
        name="unduh_nilai_abstrak",
    ),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    # HTMX views response
    path("hx/get-stats/", views_htmx.get_stats, name="hx_get_stats"),
]

hp_awards_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


def _throw_error(request):
    raise Exception("exception raised.")


urlpatterns = [
    path("try-err/", _throw_error),
    path("admin-sibijaks/", admin.site.urls),
    path("", include("hp_awards.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

hp_awards/models.py
from random import randint
import re
import uuid

from django.contrib.auth.models import User
from django.core.validators import FileExtensionValidator
from django.db import models

from django_resized import ResizedImageField

from .validators import filesize_validator

pdf_validator = FileExtensionValidator(
    allowed_extensions=["docx", "doc", "pdf", "jpg", "jpeg", "png", "bmp"]
)


def randomize_name_doc(instance, filename):
    ext = filename.split(".")[-1]
    return f"dokumen_pb_doc/{instance.kode_submisi}.{ext}"


def randomize_name_pdf(instance, filename):
    ext = filename.split(".")[-1]
    return f"dokumen_pb_pdf/{instance.kode_submisi}.{ext}"


def randomize_name_turnitin(instance, filename):
    ext = filename.split(".")[-1]
    return f"dokumen_turnitin/{instance.kode_submisi}.{ext}"


def randomize_name_ppt(instance, filename):
    ext = filename.split(".")[-1]
    return f"dokumen_ppt/{instance.kode_submisi}.{ext}"


class TimestampedModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Submisi(TimestampedModel):
    # Tahap 1: Abstrak
    # Tahap 2: Fulltext PDF
    # Tahap 3: PPT dan file final Word docx
    ht_wa = "Nomor WhatsApp (WA) yang bisa dihubungi, diawali 08"
    ht_daftar_anggota = "Tuliskan nama-nama anggota tim yang terlibat (jika ada) dipisahkan dengan tanda titik koma (;)"

    DIPLOMA12 = "d12"
    DIPLOMA3 = "d3"
    SARJANA = "s1"
    MAGISTER = "s2"
    DOKTOR = "s3"
    # PENDIDIKAN_LAINNYA = "oth"
    PENDIDIKAN_CHOICES = {
        SARJANA: "Sarjana (S1)",
        MAGISTER: "Magister (S2)",
        DOKTOR: "Doktor (S3)",
    }

    UMUM = "umum"
    MAHASISWA = "mhs"
    MAHASISWA2 = "mhs2"
    KATEGORI_PENDAFTAR_CHOICES = {
        UMUM: "Umum",
        MAHASISWA: "Mahasiswa",
        MAHASISWA2: "Mahasiswa S2",
    }

    INDIVIDU = "indiv"
    TIM = "tim"
    KATEGORI_TIM_CHOICES = {
        INDIVIDU: "Individu",
        TIM: "Tim",
    }

    kode_submisi = models.UUIDField(default=uuid.uuid4, editable=False)
    nama = models.CharField(max_length=100, help_text="Nama sesuai KTP")
    wa = models.CharField(
        max_length=15,
        verbose_name="nomor WA",
        help_text=ht_wa,
        # unique=True,
    )
    email = models.EmailField(max_length=50)
    pendidikan = models.CharField(
        choices=PENDIDIKAN_CHOICES,
        max_length=5,
        verbose_name="pendidikan terakhir",
        blank=True,
        null=True,
    )
    pekerjaan = models.CharField(
        max_length=150,
        blank=True,
        null=True,
        help_text="Contoh: analis kebijakan, dosen, peneliti, dsb",
        verbose_name="profesi",
    )
    afiliasi = models.CharField(
        max_length=150,
        blank=True,
        null=True,
        help_text="Nama institusi atau organisasi",
        verbose_name="institusi",
    )
    swafoto = ResizedImageField(
        verbose_name="pasfoto penulis utama",
        size=[None, 480],
        quality=80,
        upload_to="swafoto/",
        force_format="JPEG",
        help_text="[format JPG atau PNG] rasio 2x3 portrait",
        blank=True,
        null=True,
    )
    # ktp = ResizedImageField(
    #     verbose_name="pasfoto penulis utama",
    #     size=[640, None],
    #     quality=80,
    #     upload_to="ktp/",
    #     force_format="JPEG",
    # )
    ktm = models.FileField(
        upload_to="ktm/",
        verbose_name="KTM / surat pernyataan",
        blank=True,
        null=True,
        validators=[pdf_validator, filesize_validator],
        help_text="[format PDF atau JPG/PNG] Bukti atau pernyataan sebagai mahasiswa aktif",
    )
    judul_pb = models.CharField(
        max_length=200,
        help_text="Maksimum 200 karakter",
        verbose_name="judul Policy Brief",
    )
    abstrak_pb = models.TextField(
        verbose_name="abstrak Policy Brief",
        help_text="Maksimum 250 kata",
    )
    kategori_pendaftar = models.CharField(
        max_length=10,
        choices=KATEGORI_PENDAFTAR_CHOICES,
        # help_text="Mahasiswa S3 harus memilih Kategori Umum",
    )
    kategori_tim = models.CharField(
        max_length=10,
        choices=KATEGORI_TIM_CHOICES,
        blank=True,
        null=True,
        editable=False,
    )
    topik = models.ForeignKey(
        "Topik",
        related_name="submisi",
        on_delete=models.SET_NULL,
        verbose_name="topik penulisan",
        blank=True,
        null=True,
    )
    # policy_questions = models.ManyToManyField(
    #     "PolicyQuestion",
    #     related_name="submisis",
    #     verbose_name="policy question",
    #     help_text="minimal pilih satu",
    # )
    policy_question = models.ForeignKey(
        "PolicyQuestion",
        related_name="submisis",
        verbose_name="Policy Question",
        on_delete=models.CASCADE,
        help_text="Pilih LAINNYA jika ingin membuat Policy Question baru",
    )
    policy_question_custom = models.CharField(
        max_length=500,
        blank=True,
        null=True,
        verbose_name="Policy Question Anda",
        help_text="Anda harus menuliskan Policy Question Anda jika memilih 'LAINNYA'",
    )
    reviewers = models.ManyToManyField(
        "Reviewer",
        related_name="submisis",
        blank=True,
        through="Penilaian",
        verbose_name="reviewer",
    )
    kolaborators = models.ManyToManyField(
        "Kolaborator", related_name="submisis", blank=True, verbose_name="kolaborators"
    )
    # bool check tahapan
    nilai1 = models.DecimalField(default=0, max_digits=5, decimal_places=2)
    lolos_tahap_1 = models.BooleanField(default=False)
    nilai2 = models.DecimalField(default=0, max_digits=5, decimal_places=2)
    lolos_tahap_2 = models.BooleanField(default=False)
    nilai3 = models.DecimalField(default=0, max_digits=5, decimal_places=2)
    lolos_tahap_3 = models.BooleanField(default=False)

    # status submisi
    TUNGGU = "tunggu"
    TUNGGU2 = "tunggu2"  # tunggu penugasan juri tahap 2
    TUNGGU3 = "tunggu3"  # tunggu penugasan juri tahap 3
    IN_REVIEW = "review"
    GUGUR = "gugur"
    STATUS_CHOICES = {
        TUNGGU: "Menunggu Penilaian",
        TUNGGU2: "Menunggu Penilaian",
        TUNGGU3: "Menunggu Penilaian",
        IN_REVIEW: "Dalam Penilaian",
        GUGUR: "Gugur",
    }
    status = models.CharField(max_length=100, choices=STATUS_CHOICES, default=TUNGGU)
    # field paska penilaian abstrak
    file_pb_pdf = models.FileField(
        max_length=500,
        blank=True,
        null=True,
        upload_to=randomize_name_pdf,
        verbose_name="file PB PDF",
    )
    file_pb_doc = models.FileField(
        max_length=500,
        blank=True,
        null=True,
        upload_to=randomize_name_doc,
        verbose_name="file PB DOC",
    )
    file_turnitin = models.FileField(
        max_length=500,
        blank=True,
        null=True,
        upload_to=randomize_name_turnitin,
        verbose_name="file Turnitin",
    )
    file_pb_ppt = models.FileField(
        max_length=500,
        blank=True,
        null=True,
        upload_to=randomize_name_ppt,
        verbose_name="file PB PPT",
    )
    link_dakung = models.TextField(blank=True, null=True)

    def __str__(self):
        return f"{self.nama} - {self.judul_pb}"

    def save(self, *args, **kwargs):
        # judul upper
        judul = self.judul_pb
        self.judul_pb = str(judul).upper()
        # nama upper
        nama = self.nama
        self.nama = str(nama).upper()
        # pekerjaan upper jika ada
        if self.pekerjaan:
            pekerjaan = str(self.pekerjaan).upper()
            self.pekerjaan = pekerjaan
        # sterilkan nomor WA
        wa = self.wa
        self.wa = re.sub(r"[^\d]", "", wa)
        super().save(*args, **kwargs)

    class Meta:
        verbose_name_plural = "Submisi"
        permissions = [
            ("change_manage_submissions", "Bisa mengatur submisi"),
        ]


class Pernyataan(TimestampedModel):
    judul = models.TextField()

    def __str__(self):
        return self.judul

    class Meta:
        verbose_name_plural = "Pernyataan"


class Topik(TimestampedModel):
    judul = models.CharField(max_length=100)

    def save(self, *args, **kwargs):
        judul = self.judul
        self.judul = str(judul).upper()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.judul

    class Meta:
        verbose_name_plural = "Topik"


class PolicyQuestion(TimestampedModel):
    judul = models.CharField(max_length=500)
    sumber = models.CharField(max_length=100, blank=True, null=True)

    class Meta:
        ordering = ["id"]

    def save(self, *args, **kwargs):
        # judul = self.judul
        # self.judul = judul[0].upper() + judul[1:].lower()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.judul

    class Meta:
        verbose_name_plural = "Policy Questions"


class Kolaborator(TimestampedModel):
    nama = models.CharField(max_length=100)
    wa = models.CharField(max_length=30, verbose_name="nomor WA", blank=True, null=True)
    email = models.EmailField(max_length=70, blank=True, null=True)
    jabatan = models.CharField(max_length=100, blank=True, null=True)
    peran = models.CharField(max_length=100, blank=True, null=True)

    class Meta:
        verbose_name_plural = "Kolaborator"

    def __str__(self):
        return self.nama

    def save(self, *args, **kwargs):
        nama = self.nama
        self.nama = str(nama).upper()
        super().save(*args, **kwargs)


class Reviewer(TimestampedModel):
    # Pejabat Kementerian Kesehatan, SKM, LAN, Bappenas, Diaspora
    KEMKES = "kemkes"
    PT = "pt"
    SKM = "skm"
    LAN = "lan"
    BAPPENAS = "bappenas"
    DIASPORA = "diaspora"
    LAINNYA = "lainnya"
    KATEGORI_CHOICES = {
        KEMKES: "Pejabat Kementerian Kesehatan",

hp_awards/forms.py
from django import forms
from django.core.exceptions import ValidationError

from django_recaptcha.fields import ReCaptchaField
from django_recaptcha.widgets import ReCaptchaV3

from .models import Submisi, Reviewer, PolicyQuestion


class FormCaptcha(forms.Form):
    captcha = ReCaptchaField(widget=ReCaptchaV3)


class FormPendaftaran(forms.ModelForm):
    policy_question = forms.ModelChoiceField(
        queryset=PolicyQuestion.objects.order_by("id")
    )

    class Meta:
        model = Submisi
        fields = [
            "nama",
            "wa",
            "email",
            "kategori_pendaftar",
            "pendidikan",
            "pekerjaan",
            "afiliasi",
            # "topik",
            "policy_question",
            "policy_question_custom",
            # "swafoto",  # tidak pada saat registrasi awal
            "ktm",
            "judul_pb",
            "abstrak_pb",
        ]

    def clean(self):
        cleaned_data = super().clean()
        kategori_pendaftar = cleaned_data.get("kategori_pendaftar")
        ktm = cleaned_data.get("ktm")
        pekerjaan = cleaned_data.get("pekerjaan")
        # Mahasiswa butuh KTM/surket mhs
        if (kategori_pendaftar in (Submisi.MAHASISWA, Submisi.MAHASISWA2)) and not ktm:
            self.add_error(
                "ktm",
                "Kategori Mahasiswa harus menyertakan KTM atau surket mahasiswa",
            )

        # Umum harus mengisi kolom pekerjaan
        if kategori_pendaftar == Submisi.UMUM and not pekerjaan:
            self.add_error(
                "pekerjaan",
                "Kategori Umum harus mengisi nama profesi",
            )

        policy_question = cleaned_data.get("policy_question")
        policy_question_custom = cleaned_data.get("policy_question_custom")
        if (
            policy_question == PolicyQuestion.objects.get(pk=1)
            and not policy_question_custom
        ):
            self.add_error(
                "policy_question_custom",
                "Anda harus menuliskan Policy Question Anda jika memilih 'Lainnya'",
            )


class FormPenugasanJuri(forms.ModelForm):
    class Meta:
        model = Submisi
        fields = ["reviewers"]
        labels = {
            "reviewers": "Juri ditugaskan:",
        }


class FormUnggahFulltext(forms.ModelForm):
    class Meta:
        model = Submisi
        fields = ["file_pb_pdf", "file_pb_doc", "file_turnitin", "link_dakung"]
        labels = {
            "file_pb_pdf": "1. File Naskah format PDF",
            "file_pb_doc": "2. File Naskah format DOC/DOCX",
            "file_turnitin": "3. File Bukti Bebas Plagiarisme (misalnya Turnitin)",
            "link_dakung": "4. Link Apendiks dan Data Dukung (Jika Ada. Jangan lupa izinkan akses untuk panitia).",
        }


class FormUnggahPPT(forms.ModelForm):
    class Meta:
        model = Submisi
        fields = ["file_pb_ppt"]
        labels = {
            "file_pb_ppt": "1. File Bahan Tayang format Microsoft PowerPoint (PPT/PPTX)"
        }


class ReviewerForm(forms.ModelForm):
    # tidak perlu ada Meta karena
    # sejauh ini Form ini hanya untuk situs admin

    def clean_username(self):
        username = self.cleaned_data["username"]
        duplicate_found = Reviewer.objects.filter(username=username).exists()
        if duplicate_found and self.instance.pk is None:
            raise ValidationError("Reviewer dengan username yang sama sudah ada.")
        return username


class FormKontak(forms.Form):
    nama = forms.CharField(label="Nama", max_length=150, required=True)
    email = forms.EmailField(
        required=True, max_length=50, help_text="Kami akan merespon ke alamat email ini"
    )
    wa = forms.CharField(label="Nomor WA", max_length=20, required=False)
    pertanyaan = forms.CharField(required=True, widget=forms.Textarea)

hp_awards/templates/hp_awards/registrasi.html
{% extends 'hp_awards/BASE.html' %}
{% load static django_bootstrap5 %}

{% block title_bl %}Registrasi{% endblock %}

{% block head_bl %}
<style>
    .select2-selection--single {
        height: 100% !important;
    }

    .select2-selection__rendered{
        word-wrap: break-word !important;
        text-overflow: inherit !important;
        white-space: normal !important;
    }
</style>
{% endblock %}

{% block body_bl %}
<div class="container my-5">
    <h1 id="oo">Pendaftaran Abstrak</h1>
    <div class="fs-5 mt-4">Sebelum mendaftar, pastikan sudah membaca <a class="color-kemkes"
            href="https://drive.google.com/file/d/1K3m5kTKHjE8ewso1TMW1BYAZ6AxrbE1i/view?usp=drive_link"
            target="_blank"><b>Pedoman</b></a>
        dan menyiapkan <a class="color-kemkes" target="_blank"
            href="https://drive.google.com/file/d/1RbH3wAY3Dfq5oPT_N5o18x975uH7831B/view"><b>Surat keterangan Mahasiswa Aktif</b></a>
        (jika Anda mendaftar Kategori Mahasiswa)
    </div>
    <div class="fs-5">
        <!-- FORM ERROR MESSAGES -->
        {% if form_has_errors %}<span class="color-red fs-5">Terdapat kesalahan pengisian form. Cek teks merah</span>{% endif %}
        {{ form.non_field_errors }}
    </div>
    <form method="POST" class="my-3 form-kemkes" enctype="multipart/form-data">
        {% csrf_token %}
        <h3 class="mt-5 mb-4">Pernyataan</h3>
        <b>Dengan ini saya menyatakan:</b>
        <div id="cb-pernyataan" class="mb-5">
            {% for pernyataan in pernyataans %}
            <div class="form-check my-3">
                <input onchange="cekPernyataan()" class="form-check-input pernyataan-input" required type="checkbox" value="" id="id_pernyataan_{{ pernyataan.pk }}">
                <label class="form-check-label" for="id_pernyataan_{{ pernyataan.pk }}">{{ pernyataan }}</label>
            </div>
            {% endfor %}
        </div>
        <div id="main-form">
            <h3 class="mt-5">Biodata dan Detail Submisi</h3>
            <table id="table-biodata" class="table table-borderless table-hover ms-3" style="max-width: 960px;">
                {{ form.as_table }}
            </table>

            <h3 class="mt-5">Anggota Tim (Opsional)</h3>
            <div>Masukkan identitas anggota tim yang berkontribusi (jika ada)</div>
            <div class="px-3 pb-3 mb-5" style="max-width: 1024px;">
                <table class="mt-3 table table-sm table-borderless">
                    <thead>
                        <tr>
                            <th>Nama</th>
                            <th>Nomor WA</th>
                            <th>Email</th>
                        </tr>
                    </thead>
                    <tbody id="tbody-collab">
                        <tr class="tr-collab">
                            <td><input type="text" maxlength="100" class="form-control form-control-sm" name="kolab-nama"
                                    placeholder="Nama anggota tim"></td>
                            <td><input type="text" maxlength="30" class="wa-kolab form-control form-control-sm" name="kolab-wa" placeholder="08XXXXXXX">
                            </td>
                            <td><input type="email" maxlength="70" class="form-control form-control-sm" name="kolab-email"
                                    placeholder="email@email.com"></td>
                        </tr>
                    </tbody>
                </table>
                <button class="btn btn-sm btn-secondary" type="button" onclick="appendTr()">Tambah anggota tim lagi</button>
            </div>
            <!-- Recaptcha v3 -->
            {{ form_captcha }}
            <span class="fs-5" style="color: red;">Submisi yang sudah diunggah <b>tidak dapat diubah</b>. Mohon cek kembali isian Anda sebelum melanjutkan</span>
            <div class="d-grid gap-2">
                <button class="mt-3 btn btn-kemkes" type="submit">Kirim Submisi</button>
            </div>
        </div>
    </form>
</div>
{% endblock %}

{% block body_add_bl %}
<script>
    // Checkbox pernyataan harus dicentang semua
    // var allPernyataanChecked = true;
    // function cekPernyataan() {
    //     $(".pernyataan-input").each(function () {
    //         if (!$(this).is(":checked")) {
    //             allPernyataanChecked = false;
    //             return false; // Exit the each loop if a checkbox is not checked
    //         } else {
    //             allPernyataanChecked = true;
    //         }
    //     });
    //     if (allPernyataanChecked) {
    //         $("#main-form").show();
    //     } else {
    //         $("#main-form").hide();
    //     }
    // }
    function appendTr() {
        // Get the existing table body
        var tbody = $("#tbody-collab");

        // Clone the existing row (with ID) for new data
        var newRow = $(".tr-collab").first().clone();

        // Remove the ID from the cloned row (optional)
        // newRow.removeAttr("id");

        // Update cell content (optional)
        newRow.find("input[name='kolab-nama']").val(""); // Set name input to empty value
        newRow.find("input[name='kolab-wa']").val("");   // Set WA input to empty value
        newRow.find("input[name='kolab-email']").val(""); // Set email input to empty value

        // Append the new row to the tbody
        tbody.append(newRow);
        enforceNumeric();
    }

    $(document).ready(function () {
        // $("#main-form").hide();
        // cekPernyataan();

        // Percantik Django HTML form
        $(".form-kemkes").find("label").addClass("form-label");
        $(".form-kemkes").find("input[type='text'], input[type='email'], input[type='file'], textarea").addClass("form-control");
        $(".form-kemkes").find("select").addClass("form-select");
        $(".form-kemkes").find("br").remove();

        // NIK dan nomor WA hanya bisa diisi angka
        $("#id_nik").on("input keypress paste", function () {
            var val = $(this).val();
            $(this).val(val.replace(/[^0-9]/g, ""));
        });
        $("#id_wa").on("input keypress paste", function () {
            var val = $(this).val();
            $(this).val(val.replace(/[^0-9]/g, ""));
        });

        // Select2 untuk policy questions list
        $('#id_policy_question').select2();

        // Toggle Custom Policy question on Lainnya
        $('tr input[id="id_policy_question_custom"]').closest('tr').hide();
        if ($("#id_policy_question").val() === "1") {
            $('tr input[id="id_policy_question_custom"]').closest('tr').show();
        }
        $("#id_policy_question").change(function () {
            if ($(this).val() === "1") {
                $('tr input[id="id_policy_question_custom"]').closest('tr').show();
            } else {
                $('tr input[id="id_policy_question_custom"]').closest('tr').hide();
            }
        });

        // Toggle KTM, pendidikan, profesi based on kategori pendaftar
        $('tr input[id="id_ktm"]').closest('tr').hide();
        $('tr select[id="id_pendidikan"]').closest('tr').show();
        $('tr input[id="id_pekerjaan"]').closest('tr').hide();
        $('#id_afiliasi_helptext').text("Nama institusi atau organisasi");
        var kategoriPendaftar = $("#id_kategori_pendaftar").val();
        if (kategoriPendaftar === "mhs" || kategoriPendaftar === "mhs2") {
            $('tr input[id="id_ktm"]').closest('tr').show();
            $('tr select[id="id_pendidikan"]').closest('tr').hide();
            $('tr input[id="id_pekerjaan"]').closest('tr').hide();
            $('#id_afiliasi_helptext').text("Nama institusi pendidikan");
        }
        $("#id_kategori_pendaftar").change(function () {
            kategoriPendaftar = $(this).val();
            if (kategoriPendaftar === "mhs" || kategoriPendaftar === "mhs2") {
                $('tr input[id="id_ktm"]').closest('tr').show();
                $('tr select[id="id_pendidikan"]').closest('tr').hide();
                $('tr input[id="id_pekerjaan"]').closest('tr').hide();
                $('#id_afiliasi_helptext').text("Nama institusi pendidikan");
            } else {
                $('tr input[id="id_ktm"]').closest('tr').hide();
                $('tr select[id="id_pendidikan"]').closest('tr').show();
                $('tr input[id="id_pekerjaan"]').closest('tr').show();
                $('#id_afiliasi_helptext').text("Nama institusi atau organisasi");
            }
        });

        // gunakan select2 pada policy questions
        $('#id_policy_question').select2({width: '100%'});

        // Summernote
        $('#id_abstrak_pbx').summernote({
            toolbar: [
                // [groupName, [list of button]]
                ['style', ['bold', 'italic', 'underline', 'clear']],
                ['font', ['strikethrough', 'superscript', 'subscript']],
                // ['fontsize', ['fontsize']],
                // ['color', ['color']],
                // ['para', ['ul', 'ol', 'paragraph']],
                // ['height', ['height']]
            ],
            callbacks: {
                onChange: function (contents, $editable) {
                    var wordCount = contents.split(/\s+/).length;
                    $("#id_abstrak_pb_helptext").text(wordCount + " / 250 kata");

                    // if (wordCount > maxWords) {
                    //     // Remove extra words
                    //     var trimmedText = contents.split(/\s+/, maxWords).join(" ");
                    //     $('#id_abstrak_pb').summernote('reset');
                    //     $('#id_abstrak_pb').summernote('pasteHTML', trimmedText);
                    //     // $(this).val(trimmedText);
                    //     // $("#wordCount").text(maxWords + " words (limit reached)");
                    // }
                }
            }
        });

        // Hitung jumlah karakter per maks karakter pada textarea abstrak PB
        var maxWords = 251;
        $("#id_abstrak_pb").keyup(function () {
            var wordCount = $(this).val().split(/\s+/).length;
            $("#id_abstrak_pb_helptext").text(wordCount + " / 250 kata");

            if (wordCount > maxWords) {
                // Remove extra words
                var trimmedText = $(this).val().split(/\s+/, maxWords).join(" ");
                $(this).val(trimmedText);
                // $("#wordCount").text(maxWords + " words (limit reached)");
            }
        });

        // Pada dynamic form kolaborator, WA hanya angka
        enforceNumeric();

        // HANYA UNTUK DEMO
        // Hide Mahasiswa S2
        $("#id_kategori_pendaftar option[value='mhs2']").remove();
    });
    
    function enforceNumeric() {
        // Pada dynamic form kolaborator, WA hanya angka
        $(".wa-kolab").on("input keypress paste", function () {
            var val = $(this).val();
            $(this).val(val.replace(/[^0-9]/g, ""));
        });
    }
</script>
{% endblock %}

hp_awards/templates/hp_awards/registrasi_sukses.html
{% extends 'hp_awards/BASE.html' %}
{% load static django_bootstrap5 %}

{% block title_bl %}Registrasi{% endblock %}

{% block body_bl %}
<div class="container my-5">
    <p class="fs-3">Registrasi sukses</p>
    <p class="fs-5">Gunakan nomor WA dan email Anda untuk melihat status submisi</p>
    <ul>
        <li>No WA Anda: {{ wa }}</li>
        <li>Email Anda: {{ email }}</li>
    </ul>
    <p><a href="{% url 'hp_awards:list_submisi' %}" class="color-kemkes">Lihat status submisi</a></p>
</div>
{% endblock %}